const useJsonLD = () => {
  // const { locale, asPath } = useRouter();

  const defaultJson = {
    '@context': 'http://schema.org',
    '@type': 'Organization',
    name: 'Create Next App',
    description: 'Generated by create next app',
    keywords: 'react, javascript, next.js',
    // url: `${DOMAIN}/${locale}${asPath}`,
    // logo: `${DOMAIN}/static/media/logo.346e8bbf41c83d6c4617e879ec540130.svg`,
  };

  return { ...defaultJson };
};

export default useJsonLD;
