name: Lighthouse CI

on: pull_request

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: npm install, build
        run: |
          npm install
          npm run build

      #      - name: run Lighthouse CI
      #        id: lighthouse_audit
      #        env:
      #          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      #        run: |
      #          npm install -g @lhci/cli@0.12.x
      #          lhci autorun

      - name: Audit URLs using Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            http://localhost:3000/
          budgetPath: './.github/workflows/lighthouse/budget.json'
          configPath: './lighthouserc.js'
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Format lighthouse score
        id: format_lighthouse_score
        uses: actions/github-script@v6
        with:
          script: |
            const lighthouseCommentMaker = require('./.github/workflows/lighthouse/lighthouseCommentMaker.js');

            const lighthouseOutputs = {
              manifest: ${{ steps.lighthouse_audit.outputs.manifest }},
              links: ${{ steps.lighthouse_audit.outputs.links }}
            };

            const comment = lighthouseCommentMaker({ lighthouseOutputs });
            core.setOutput("comment", comment);

#      - name: Add Lighthouse stats as comment
#        id: comment_to_pr
#        uses: marocchino/sticky-pull-request-comment@v2
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          number: ${{ github.event.pull_request.number }}
#          header: lighthouse
#          message: ${{ steps.format_lighthouse_score.outputs.comment }}